apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: retrodep-rqxv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: retrodep-rqxv
    app.kubernetes.io/part-of: test-app-514
  name: retrodep-rqxv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-retrodep
      app.kubernetes.io/instance: retrodep-rqxv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-retrodep
        app.kubernetes.io/instance: retrodep-rqxv
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-514/retrodep-rqxv@sha256:340d7daa9115ae309f49873fdcc898946f5354da37d82d7ab8c0fd4b8469e846
        name: my-retrodep
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
