apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: maven-hello-world-fgsa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: maven-hello-world-fgsa
    app.kubernetes.io/part-of: test-app-514
  name: maven-hello-world-fgsa
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: maven-hello-world-fgsa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: maven-hello-world-fgsa
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-514/maven-hello-world-fgsa@sha256:8541691a62cea1a6626d8bd7ee204d484debb7fcf454715e62c051bd75d9f2dd
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
